### ISSUE TITLE
DevOps Fix: Test fails because of wrong path.

### ISSUE THREAD

**Issue by SVYSHE** [SVYSHE/Jobb#4]
![image](https://user-images.githubusercontent.com/58707844/99972399-c057e300-2d9e-11eb-8b83-91a507f5af3b.png)

- [ ] EmptyDirectoryJobTest needs to be adjusted to the TestBase

**Comment by SVYSHE** [comment]
@eldtt Müsste sich erledigt haben, wenn wir stattdessen auf die TestBase wechseln.

**Comment by eldtt** [comment]
Ist nun gefixed.
Branch: DevOpsFix_issue#4
